#!/bin/bash

# docker build --tag 157239n/webhook-explorer .
docker compose -f docker-compose.prod.yml build
docker compose -f docker-compose.prod.yml down
docker compose -f docker-compose.prod.yml up -d


